using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;


namespace beachmaster.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<beachMasterEntities>
    {
        protected override void Seed(beachMasterEntities context)
        {
            context.beach.Add(new beach { beachId = 1, name = "Beach 1", description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "40.37.91820111976663", longitude = "23.772354125976562", numReviews = 2, rate = 1, approved = true, votes = 5 });
            context.beach.Add(new beach { beachId = 2, name = "Beach 2", description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "37.975056262053606", longitude = "23.76317024230957", numReviews = 3, rate = 2, approved = true, votes = 5 });
            context.beach.Add(new beach { beachId = 3, name = "Beach 3", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.01824350277631", longitude = "23.793447017669678", numReviews = 2, rate = 3, approved = true, votes = 7 });
            context.beach.Add(new beach { beachId = 4, name = "Beach 4", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.019731098561124", longitude = "23.798468112945557", numReviews = 1, rate = 4, approved = true, votes = 1 });
            context.beach.Add(new beach { beachId = 5, name = "Beach 5", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.016045862841416", longitude = "23.79563570022583", numReviews = 1, rate = 3, approved = false, votes = 8 });
            context.beach.Add(new beach { beachId = 6, name = "Beach 6", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.01614729382738", longitude = "23.79160165786743", numReviews = 1, rate = 4, approved = true, votes = 9 });
            context.beach.Add(new beach { beachId = 7, name = "Beach 7", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.01499773443347", longitude = "23.81511926651001", numReviews = 1, rate = 2, approved = false, votes = 12 });
            context.beach.Add(new beach { beachId = 8, name = "Beach 8", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.021996243234476", longitude = "23.784048557281494", numReviews = 1, rate = 4, approved = true, votes = 4 });
            context.beach.Add(new beach { beachId = 9, name = "Beach 9", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.01087269642645", longitude = "23.784263134002686", numReviews = 1, rate = 5, approved = false, votes = 4 });
            context.beach.Add(new beach { beachId = 10, name = "Beach 10", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.01073744534838", longitude = "23.803446292877197", numReviews = 1, rate = 2, approved = true, votes = 2 });
            context.beach.Add(new beach { beachId = 11, name = "Beach 11", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.02169197414036", longitude = "23.81232976913452", numReviews = 1, rate = 3, approved = false, votes = 1 });
            context.beach.Add(new beach { beachId = 12, name = "Beach 12", description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque fermentum erat, eu auctor velit tincidunt a. Cras mattis adipiscing.", latitude = "38.017803980061146", longitude = "23.806021213531494", numReviews = 1, rate = 2, approved = true, votes = 5 });

            context.review.Add(new review { reviewId = 1, name = "Review 1", beachId = 1, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 2, name = "Review 2", beachId = 2, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 3, name = "Review 3", beachId = 3, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 4, name = "Review 4", beachId = 4, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 5, name = "Review 5", beachId = 5, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 6, name = "Review 6", beachId = 6, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 7, name = "Review 7", beachId = 7, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 8, name = "Review 8", beachId = 8, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 9, name = "Review 9", beachId = 9, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 10, name = "Review 10", beachId = 3, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 11, name = "Review 11", beachId = 2, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 12, name = "Review 12", beachId = 2, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
            context.review.Add(new review { reviewId = 13, name = "Review 13", beachId = 1, reviewDate = System.DateTime.Now, text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vestibulum tellus sapien, vitae vulputate felis volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec auctor suscipit pulvinar. Quisque enim lacus, mollis ac orci vitae, auctor tempus nulla. Pellentesque sed vestibulum sapien, eget blandit tortor. Curabitur dictum metus et placerat porttitor. Phasellus neque tellus, viverra et placerat at, fermentum in nisi. Fusce venenatis fermentum diam, vitae ultricies nulla accumsan sit amet. Nulla posuere turpis a bibendum semper. Morbi porta sapien gravida pharetra congue. Donec eu magna auctor tortor consequat bibendum. Donec nec suscipit nisl." });
        }
    }
}